version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
      - "5433:5432"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    command: >
      sh -c "  python manage.py wait_for_db && 
               python manage.py migrate && 
               python manage.py runserver 0.0.0.0:8000"

    environment:
      # DATABASE CONNECTION PARAMS
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      # DJANGO SECRET KEY
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
  db:
    image: postgis/postgis
    # build:
    #   context: ./db_image
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword