# Generated by Django 2.1.15 on 2020-07-04 15:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tilebox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=3857),
        ),
    ]
