# Generated by Django 2.1.15 on 2020-07-04 16:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200704_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
